# Generated by Django 3.2.7 on 2021-09-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodelv2',
            old_name='body',
            new_name='hi',
        ),
    ]
