# Generated by Django 3.2.7 on 2021-09-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_body_todomodelv2_hi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodelv2',
            old_name='hi',
            new_name='title',
        ),
    ]
