# Generated by Django 3.2.7 on 2021-09-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_hi_todomodelv2_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodelv2',
            old_name='title',
            new_name='body',
        ),
    ]
