# Generated by Django 3.2.7 on 2021-09-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_title_todomodelv2_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='is_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todomodelv2',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
